### ISSUE TITLE
Implement font table

### ISSUE THREAD

**Issue by genebot** [openxml/openxml-docx#27]
_From the docs_:

> The next component of a WordprocessingML document is storing information about the fonts used in the document. WordprocessingML stores two pieces of information about fonts:
> - (optionally) Information about the font to enable font substitution. Font substitution is a process by which an application, when it cannot locate a specific font, attempts to locate the closest possible match to the intended appearance of the font
>   ￼660
> - (optionally) One or more embedded forms of the font for use on systems which do not have access to the font. When fonts are embedded, they are obfuscated to ensure that they are only used to view the contents of the document in which they are embedded, and for no other purpose.
## Tasks:
- [ ] Implement font table class (a)
- [ ] Implement font class (b)
- [ ] Add alternate name property (c)
- [ ] Add charset property (d)
- [ ] Add embedded bold property (e)
- [ ] Add embedded bold italic property (f)
- [ ] Add embedded italic property (g)
- [ ] Add embedded regular property (h)
- [ ] Add embedded system fonts property (i)
- [ ] Add embedded true type fonts property (j)
- [ ] Add font family property (k)
- [ ] Add not true type property (l)
- [ ] Add Panose1 property (m)
- [ ] Add pitch property (n)
- [ ] Add subset fonts property (o)
- [ ] Add sig property (p)
- [ ] Support adding the font table to the package (q)
- [ ] Support adding fonts to the font table (r)
